server:
  port: 8082

spring:
  application:
    name: agent-app

  ai:
    dashscope:
      api-key: ${YOKA_DASHSCOPE_API_KEY}
      chat:
        model: qwen3.7-plus

# MCP Server 连接配置
mcp:
  server:
    url: http://localhost:8081
    endpoint: /mcp
    token: mcp_xxxxx


# 接口分组配置
springdoc:
  group-configs:
    - group: 'agent'
      display-name: 'Agent'
      paths-to-match: '/**'
      packages-to-scan: 'com.example.agent.controller'